stages:
 - update

update-job:
  stage: update
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - git clone https://gitlab-ci-token:$ACCESS@git.coagulate.net/CoagulateSL/LSLR.git || exit 1
    - cd LSLR || exit 1
    - git pull --recurse-submodules || exit 1
    - git submodule init || exit 1
    - git submodule update --remote --recursive || exit 1
    - git config --global user.name 'GitLab bot'
    - git config --global user.email 'gitlabbot@predestined.net'
    - git commit -am "Updated JSLBot" && git push || echo "No changes to commit"
